apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: visit-counter-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visitor
  template:
    metadata:
     name: visit-counter
     labels:
       app: visitor
    spec:
      containers:
      - name: python-app
        image: ragav1294/visits-counter:v0.0.1
